---
title: "R Bioconductor"
---


- https://www.bioconductor.org/

```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite()
```

- The Bioconductor 2018 Workshop Compilation
https://bioconductor.github.io/BiocWorkshops/index.html

https://github.com/Bioconductor/BiocWorkshops


```{r eval=FALSE, include=FALSE, echo=TRUE}
fname <- file.choose()
fname
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
file.exists(fname)
```


https://raw.githubusercontent.com/Bioconductor/BiocWorkshops/master/100_Morgan_RBiocForAll/ALL-phenoData.csv

```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata <- read.csv(fname)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
dim(pdata)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
head(pdata)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
tail(pdata)
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
summary(pdata)
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
class(fname)
class(pdata)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata <- read.csv(
    fname,
    colClasses = c("character", "factor", "integer", "factor")
)
summary(pdata)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata[1:5, c("sex", "mol.biol")]
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata[1:5, c(2, 3)]
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata[1:5, ]
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata$age
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata[["age"]]
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
class(pdata$age)
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
table(pdata$mol.biol)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
table(is.na(pdata$age))

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
levels(pdata$sex)

```

```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata$sex == "F"

```

```{r eval=FALSE, include=FALSE, echo=TRUE}
(pdata$sex == "F") & (pdata$age > 50)

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
table( pdata$mol.biol )

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pdata$mol.biol %in% c("BCR/ABL", "NEG")

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
subset(pdata, sex == "F" & age > 50)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
bcrabl <- subset(pdata, mol.biol %in% c("BCR/ABL", "NEG"))
dim( bcrabl )
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
table(bcrabl$mol.biol)
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
str(bcrabl$mol.biol)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
factor(bcrabl$mol.biol)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
bcrabl$mol.biol <- factor(bcrabl$mol.biol)
table(bcrabl$mol.biol)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
str(bcrabl$mol.biol)
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
boxplot(age ~ mol.biol, bcrabl)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
t.test(age ~ mol.biol, bcrabl)
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
library(ggplot2)
ggplot(bcrabl, aes(x = mol.biol, y = age))
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
ggplot(bcrabl, aes(x = mol.biol, y = age)) + geom_boxplot()
```





```{r eval=FALSE, include=FALSE, echo=TRUE}
if (!"BiocManager" %in% rownames(installed.packages()))
    install.packages("BiocManager", repos="https://cran.r-project.org")
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
BiocManager::install(c("rtracklayer", "GenomicRanges"))
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
BiocManager::valid()
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
BiocManager::available("TxDb.Hsapiens")
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
browseVignettes("simpleSingleCell")
```


https://support.bioconductor.org/


https://bioconductor.org/help/course-materials/


```{r eval=FALSE, include=FALSE, echo=TRUE}
library("rtracklayer")
library("GenomicRanges")
```


https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=578954849_wF1QP81SIHdfr8b0kmZUOcsZcHYr&clade=mammal&org=Human&db=hg38&hgta_group=regulation&hgta_track=knownGene&hgta_table=0&hgta_regionType=genome&position=chr9%3A133252000-133280861&hgta_outputType=primaryTable&hgta_outFileName=

```{r eval=FALSE, include=FALSE, echo=TRUE}
fname <- file.choose()
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
cpg <- rtracklayer::import(fname)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
file.exists(fname)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
cpg
```



https://bioconductor.github.io/BiocWorkshops/r-and-bioconductor-for-everyone-an-introduction.html


---

- **Introduction to Bioconductor**

https://www.datacamp.com/community/tutorials/intro-bioconductor



```{r eval=FALSE, include=FALSE, echo=TRUE}
source("https://bioconductor.org/biocLite.R")
biocLite()
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
source("https://bioconductor.org/biocLite.R")
biocLite(c( "Biostrings", "GenomicRanges", "IMMAN"))
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
library(Biostrings)

dnaSequence <- DNAStringSet( c("AAACTG", "CCCAACCA") )
dnaSequence

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
complement(dnaSequence)

```


Important packages:  
- DNAStringSet  
- Biostrings  
- GenomicRanges  

```{r eval=FALSE, include=FALSE, echo=TRUE}
library(GenomicRanges)

grangeObj <-
  GRanges(seqnames =
            Rle(c("chr1", "chr2", "chr1", "chr3"), c(1, 3, 2, 4)),
          ranges =
            IRanges(1:10, end = 7:16, names = head(letters, 10)),
          strand =
            Rle(strand(c("-", "+", "*", "+", "-")),
                c(1, 2, 2, 3, 2)),
          score = 1:10,
          GC = seq(1, 0, length=10))


grangeObj
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
seqnames(grangeObj)

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
ranges(grangeObj)

```



```{r eval=FALSE, include=FALSE, echo=TRUE}
strand(grangeObj)

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
library("clusterProfiler")

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
library("DOSE")

```


```{r eval=FALSE, include=FALSE, echo=TRUE}
library("org.Hs.eg.db")

```



```{r eval=FALSE, include=FALSE, echo=TRUE}
data(geneList, package="DOSE")

gene <- names(geneList)[abs(geneList) > 2]
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
ego <- enrichGO(gene          = gene,
                universe      = names(geneList),
                OrgDb         = org.Hs.eg.db,
                ont           = "CC",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE)

head(ego)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
emapplot(ego)

```



```{r eval=FALSE, include=FALSE, echo=TRUE}
class(dnaSequence)
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
methods(class = "DNAStringSet")

```



---

https://bioconductor.org/packages


https://support.bioconductor.org/


http://bioconductor.org/help/course-materials/


---












