---
title: "My R Codes For Data Analysis"
subtitle: "In this repository I am going to collect `R codes` for data analysis. Codes are from various resources and I try to give original link as much as possible."
author: "[Serdar Balcı, MD, Pathologist](https://www.serdarbalci.com/)"
date: '`r format(Sys.Date())`'
output: 
  html_notebook: 
    fig_caption: yes
    highlight: tango
    number_sections: yes
    theme: paper
    toc: yes
    toc_depth: 5
    toc_float: yes
  html_document: 
    code_folding: hide
    df_print: kable
    keep_md: yes
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float: yes
    highlight: kate
---

## Descriptive Statistics


```{r}
Epi::stat.table(gender,mean(age), data = scabies)

```

```{r}
table <- Epi::stat.table(gender,mean(age), data = scabies)

pander::pander(table)


```

```{r}
#Tabulate, by gender, the mean age from the scabies dataset

Epi::stat.table(gender,list(mean(age),median(age)), data = scabies)
```

```{r}
summary_data <- arsenal::tableby(gender~age+scabies_infestation,data=scabies)
summary(summary_data)

```


## skimr

https://cran.r-project.org/web/packages/skimr/vignettes/Using_skimr.html

```{r}
require(skimr)
```

```{r}
summary(iris)
```

```{r}
summary(iris$Sepal.Length)
```


```{r}
fivenum(iris$Sepal.Length)
```


```{r}
summary(iris$Species)
```


```{r}
skim(iris)
```


```{r}
iris_results <- skim(iris)
str(iris_results)
iris_results$variable
iris_results$type
```


```{r}
skimr::skim(iris) %>%
  dplyr::filter(stat == "mean")
```

```{r}
head(iris_results, n=15)
```



```{r}
mtcars %>%
  dplyr::group_by(gear) %>%
  skim()
```



```{r}
skim(iris, Sepal.Length, Species)
```


```{r}
skim(iris, starts_with("Sepal"))
```



```{r}
skim(datasets::lynx)
```


- Exploratory Data Analysis in R (introduction)


https://blog.datascienceheroes.com/exploratory-data-analysis-in-r-intro/


```{r}
library(tidyverse)
library(summarytools)
# library(funModeling) 
library(tidyverse) 
library(Hmisc)

basic_eda <- function(data)
{
  glimpse(data)
 # df_status(data)
 # freq(data) 
 # profiling_num(data)
 # plot_num(data)
  describe(data)
}

basic_eda(irisdata)
```

---

- **What's so hard about histograms?**

http://tinlizzie.org/~aran/histograms/





