---
title: "Linear Regression"
---

https://www.datacamp.com/community/tutorials/linear-regression-R

```{r, include=FALSE}
library(readxl)
ageandheight <- read_excel("data/ageandheight.xls", sheet = "Hoja2") 
lmHeight = lm(height~age, data = ageandheight)
summary(lmHeight)
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
lmHeight2 = lm(height~age + no_siblings, data = ageandheight)
summary(lmHeight2)
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
lmHeight2$coefficients
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
lmHeight2$residuals
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
pressure <- read_excel("data/pressure.xlsx")
lmTemp <- lm(Pressure~Temperature, data = pressure)
summary(lmTemp)
plot(pressure, pch = 16, col = "blue")
abline(lmTemp)
```

```{r eval=FALSE, include=FALSE, echo=TRUE}
plot(lmTemp$residuals, pch = 16, col = "red")
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
lmTemp2 = lm(Pressure~Temperature + I(Temperature^2), data = pressure) #Create a linear regression with a quadratic coefficient
summary(lmTemp2) #Review the results
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
plot(lmTemp2$residuals, pch = 16, col = "red")
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
ageandheight[2, 2] = 7.7
head(ageandheight)
```


```{r eval=FALSE, include=FALSE, echo=TRUE}
lmHeight3 = lm(height~age, data = ageandheight)#Create the linear regression
summary(lmHeight3)#Review the results
plot(cooks.distance(lmHeight3), pch = 16, col = "blue") #Plot the Cooks Distances.
```



```{r eval=FALSE, include=FALSE, echo=TRUE}
plot(cooks.distance(lmHeight), pch = 16, col = "blue")
```


