---
title: "R Notebook"
output: html_notebook
---


- R Markdown: The Definitive Guide

https://bookdown.org/yihui/rmarkdown/




## Use R Markdown

https://andrewbtran.github.io/NICAR/2018/workflow/docs/02-rmarkdown.html

- Troubleshooting in R Markdown

https://smithcollege-sds.github.io/sds-public/rmarkdown_problems.html

> {r global_options, include=FALSE}
> knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/', echo=FALSE, warning=FALSE, message=FALSE, include = FALSE)


    {r global_options, include=FALSE}
    knitr::opts_chunk$set(fig.width = 12, fig.height = 8, fig.path = 'Figs/', echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, eval = TRUE, tidy = TRUE, comment = NA)




http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html

- Knitr & R Markdown

https://kbroman.org/knitr_knutshell/pages/overview.html

https://kbroman.org/knitr_knutshell/pages/Rmarkdown.html

https://kbroman.org/knitr_knutshell/pages/markdown.html

 
- render markdown via code

*inside R*
```
markdown::markdownToHTML('markdown_example.md', 'markdown_example.html')
```

*command line*
```
R -e "markdown::markdownToHTML('markdown_example.md', 'markdown_example.html')"
```


- pandoc Rstudio integration

*command line*
```
export PATH=$PATH:/Applications/RStudio.app/Contents/MacOS/pandoc
```


```
R -e "rmarkdown::render('markdown_example.md')"
```


---

https://gist.github.com/MinhasKamal/7fdebb7c424d23149140

root                         ┌───────────────────────┐             ┌──────────────┐
 ├─branch-1                  |        Vehicle        ├── has-a ───→|    Engine    |
 │  ├─sub-branch-1           └───────────────────────┘             └──────────────┘
 │  └─sub-branch-2                 ↑              ↑                      ↑   ↑                 ------\\
 ├─branch-2                        |              |                      |   |                 ┤ ^_^ |
 │  └─sub-branch-3                 |            is-a                     |   |                 └──-──┘  
 │     ├─a                         |              |                      |   |       
 │     └─b                         |         ┌────┴─────────┐            |   |
 ├─branch-3                       is-a       |    Toyota    ├── has-a ───┘   |                 ------\\
 │  └─sub-branch-4                 |         └──────────────┘                |                 ┤ @_@ |
 └─branch-4                        |                                       is-a                └──-──┘
    ├─sub-branch-5                 |                                         |       
    ├─sub-branch-6           ┌─────┴──────────┐                     ┌────────┴────┐
    │  └─c                   │   Lamborghini  ├───────has-a ───────→│  V12 Engine │
    └─sub-branch-7           └────────────────┘                     └─────────────┘
   
    
---   


root                    
 ├─branch-1             
 │  ├─sub-branch-1          
 │  └─sub-branch-2          
 ├─branch-2             
 │  └─sub-branch-3        
 │     ├─a              
 │     └─b              
 ├─branch-3             
 │  └─sub-branch-4      
 └─branch-4             
    ├─sub-branch-5      
    ├─sub-branch-6      
    │  └─c              
    └─sub-branch-7      
    
 
   





