---
title: "R tidymodels"
output: html_notebook
---


https://www.tidymodels.org/start/models/



```r

# library(tidymodels)  # for the parsnip package, along with the rest of tidymodels

# Helper packages
# library(readr)       # for importing data
```



```{r eval=FALSE, include=FALSE}
urchins <-
  # Data were assembled for a tutorial 
  # at https://www.flutterbys.com.au/stats/tut/tut7.5a.html
  read_csv("https://tidymodels.org/start/models/urchins.csv") %>% 
  # Change the names to be a little more verbose
  setNames(c("food_regime", "initial_volume", "width")) %>% 
  # Factors are very helpful for modeling, so we convert one column
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))
#> Parsed with column specification:
#> cols(
#>   TREAT = col_character(),
#>   IV = col_double(),
#>   SUTW = col_double()
#> )
```


```{r eval=FALSE, include=FALSE}
ggplot(urchins,
       aes(x = initial_volume, 
           y = width, 
           group = food_regime,
           col = food_regime
           )
       ) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) +
  scale_color_viridis_d(option = "plasma", end = .7)

#> `geom_smooth()` using formula 'y ~ x'

```





















