
# Recommendations for Using summarytools With Rmarkdown 
author:  Dominic Comtois 
date:   
output: 
  rmarkdown::html_vignette: 
    css: 
    - !expr system.file( rmarkdown/templates/html_vignette/resources/vignette.css , package =  rmarkdown )
    - !expr system.file( includes/stylesheets/summarytools.css , package =  summarytools )
vignette: >
  %\VignetteIndexEntry{Recommendations for Rmarkdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}



```
{r, include=FALSE}
library(knitr)
opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=TRUE, results='asis')
library(summarytools)
```

This document uses theme `{r # markdown::html_vignette`.

Below are examples using recommended styles for *Rmarkdown* rendering. Available styles in
summarytools are the same as `pander`'s: 

- _simple_ (default)  
- _rmarkdown_  
- _grid_  
- _multiline_  
 
For `freq()`, `descr()` (and `ctable()`, although with caveats), _rmarkdown_ style is recommended. For
`dfSummary()`, _grid_ is recommended.
 
## Important Note

`knitr` option `{r # esults = 'asis'` must be specified to get good results. This can be done globally via
`opts_chunk$set(results='asis')`, or in the individual chunks.

The following summarytools global options have been set:
```
{r eval=FALSE, include=FALSE, echo=TRUE}
#st_options('headings', TRUE)
st_options('bootstrap.css', FALSE)
st_options('footnote', NA)
``` 

## Using method = 'render'

To generate tables using summarytool's own html rendering, the _.Rmd_ document's configuration part
(yaml) must point to the package's `summarytools.css` file. This can be achieved in several ways;
the current vignette uses this configuration:

````
output: 
  rmarkdown::html_vignette: 
    css: 
    - !expr system.file( rmarkdown/templates/html_vignette/resources/vignette.css , package =  rmarkdown )
    - !expr system.file( includes/stylesheets/summarytools.css , package =  summarytools )
````

An alternative is to point to the directory on your system containing _summarytools.css_:

````

# RMarkdown using summarytools 
output: 
  html_document: 
    css: C:/R/win-library/3.4/summarytools/includes/stylesheets/summarytools.css

````

Starting with `freq()`, we'll review the recommended methods and styles to get going with _summarytools_
in _Rmarkdown_ documents.

Jump to...

- [ctable()](#ctable)  
- [descr()](#descr)  
- [dfSummary()](#dfsummary)  


--

# freq()

`freq()` is best used with `style = 'rmarkdown'; html rendering is also possible.

## Rmarkdown Style
```
{r eval=FALSE, include=FALSE, echo=TRUE}
freq(tobacco$gender, style = 'rmarkdown')
```


## HTML Rendering
```
{r eval=FALSE, include=FALSE, echo=TRUE}
print(freq(tobacco$gender), method = 'render')
```

If you find the table too large, you can use `table.classes = 'st-small'` - an example is provided 
further below.

--

<a href= #top >Back to top</a>

# ctable() {#ctable}

## Rmarkdown Style

Tables with heading spanning over 2 rows are not fully supported in markdown (yet), but the result is 
getting close to acceptable. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
ctable(tobacco$gender, tobacco$smoker, style = 'rmarkdown')
```

## HTML Rendering

For best results, use this method.

```
{r include=FALSE, eval=FALSE, echo = TRUE}
print(ctable(tobacco$gender, tobacco$smoker), method = 'render')
```

--
 
<a href= #top >Back to top</a>
 
# descr() 3 {#descr3}

`descr()` is also best used with `style = 'rmarkdown'`, and HTML rendering is also supported.

## Rmarkdown Style
```
{r eval=FALSE, include=FALSE, echo=TRUE}
descr(tobacco, style = 'rmarkdown')
```


## HTML Rendering

We'll use table.classes = 'st-small' to show how it affects the table's size (compare to the `freq()`
table rendered earlier).

```
{r eval=FALSE, include=FALSE, echo=TRUE}
print(descr(tobacco), method = 'render', table.classes = 'st-small')
```
 
--

<a href= #top >Back to top</a>

# dfSummary() {#dfsummary}

## Grid Style

This gives good results, although the histograms are not shown. This has to do with an unresolved issue,
but we're working hard to figure out a solution. Don't forget to specify `plain.ascii = FALSE`, or
you won't get good results.

```
{r , results='asis'}
dfSummary(tobacco, style = 'grid', plain.ascii = FALSE)
```

## HTML Rendering

Although the results are not as neat as they are when simply generating an html report from 
the R interpreter -- the transparency of the graphs is lost in translation --, this is the
best method still.

```
{r eval=FALSE, include=FALSE, echo=TRUE}
print(dfSummary(tobacco, graph.magnif = 0.75), method = 'render')
```

<a href= #top >Back to top</a>
