---
title: "My R Codes For Data Analysis"
subtitle: "In this repository I am going to collect `R codes` for data analysis. Codes are from various resources and I try to give original link as much as possible."
author: "[Serdar Balcı, MD, Pathologist](https://www.serdarbalci.com/)"
date: '`r format(Sys.Date())`'
output: 
  html_notebook: 
    fig_caption: yes
    highlight: tango
    number_sections: yes
    theme: paper
    toc: yes
    toc_depth: 5
    toc_float: yes
  html_document: 
    code_folding: hide
    df_print: kable
    keep_md: yes
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float: yes
    highlight: kate
---

## Survival Analysis in R


https://rviews.rstudio.com/2017/09/25/survival-analysis-with-r/


```{r}
library(survival)
library(ranger)
library(ggplot2)
library(dplyr)
library(ggfortify)
```


```{r}
data(veteran)
head(veteran)
```

### Censored Data

```{r}
km <- with(veteran, Surv(time, status))

head(km,80)

```


### Kaplan Meier 

```{r}
km_fit <- survfit(Surv(time, status) ~ 1, data = veteran)

km_fit
```


### Life Table

```{r}
summary(km_fit, times = c(1,30,60,90*(1:10)))

```

### KM Graph Overall

```{r}
plot(km_fit, xlab="Days", main = 'Kaplan Meyer Plot') #base graphics is always ready

```


```{r}
autoplot(km_fit)

```


### KM per treatment group


```{r}
km_trt_fit <- survfit(Surv(time, status) ~ trt, data = veteran)
km_trt_fit

```


### KM Graph per treatment group


```{r}
autoplot(km_trt_fit)
```










<!-- vet <- mutate(veteran, AG = ifelse((age < 60), "LT60", "OV60"), -->
<!--               AG = factor(AG), -->
<!--               trt = factor(trt,labels=c("standard","test")), -->
<!--               prior = factor(prior,labels=c("N0","Yes"))) -->

<!-- km_AG_fit <- survfit(Surv(time, status) ~ AG, data = vet) -->
<!-- km_AG_fit -->

<!-- autoplot(km_AG_fit) -->


<!-- Fit Cox Model -->
<!-- cox <- coxph(Surv(time, status) ~ trt + celltype + karno + diagtime + age + prior , data = vet) -->
<!-- cox -->
<!-- summary(cox) -->

<!-- cox_fit <- survfit(cox) -->
<!-- cox_fit -->
<!-- plot(cox_fit, main = "cph model", xlab="Days") -->
<!-- autoplot(cox_fit) -->

<!-- aa_fit <-aareg(Surv(time, status) ~ trt + celltype + -->
<!--                    karno + diagtime + age + prior ,  -->
<!--                data = vet) -->
<!-- aa_fit -->


<!-- #summary(aa_fit)  # provides a more complete summary of results -->
<!-- autoplot(aa_fit) -->


<!-- # ranger model -->
<!-- r_fit <- ranger(Surv(time, status) ~ trt + celltype +  -->
<!--                     karno + diagtime + age + prior, -->
<!--                 data = vet, -->
<!--                 mtry = 4, -->
<!--                 importance = "permutation", -->
<!--                 splitrule = "extratrees", -->
<!--                 verbose = TRUE) -->


<!-- # Average the survival models -->
<!-- death_times <- r_fit$unique.death.times  -->
<!-- surv_prob <- data.frame(r_fit$survival) -->
<!-- avg_prob <- sapply(surv_prob,mean) -->

<!-- # Plot the survival models for each patient -->
<!-- plot(r_fit$unique.death.times,r_fit$survival[1,],  -->
<!--      type = "l",  -->
<!--      ylim = c(0,1), -->
<!--      col = "red", -->
<!--      xlab = "Days", -->
<!--      ylab = "survival", -->
<!--      main = "Patient Survival Curves") -->

<!-- # -->
<!-- cols <- colors() -->
<!-- for (n in sample(c(2:dim(vet)[1]), 20)){ -->
<!--     lines(r_fit$unique.death.times, r_fit$survival[n,], type = "l", col = cols[n]) -->
<!-- } -->
<!-- lines(death_times, avg_prob, lwd = 2) -->
<!-- legend(500, 0.7, legend = c('Average = black')) -->


<!-- vi <- data.frame(sort(round(r_fit$variable.importance, 4), decreasing = TRUE)) -->
<!-- names(vi) <- "importance" -->
<!-- head(vi) -->


<!-- cat("Prediction Error = 1 - Harrell's c-index = ", r_fit$prediction.error) -->


<!-- # Set up for ggplot -->
<!-- kmi <- rep("KM",length(km_fit$time)) -->
<!-- km_df <- data.frame(km_fit$time,km_fit$surv,kmi) -->
<!-- names(km_df) <- c("Time","Surv","Model") -->

<!-- coxi <- rep("Cox",length(cox_fit$time)) -->
<!-- cox_df <- data.frame(cox_fit$time,cox_fit$surv,coxi) -->
<!-- names(cox_df) <- c("Time","Surv","Model") -->

<!-- rfi <- rep("RF",length(r_fit$unique.death.times)) -->
<!-- rf_df <- data.frame(r_fit$unique.death.times,avg_prob,rfi) -->
<!-- names(rf_df) <- c("Time","Surv","Model") -->

<!-- plot_df <- rbind(km_df,cox_df,rf_df) -->

<!-- p <- ggplot(plot_df, aes(x = Time, y = Surv, color = Model)) -->
<!-- p + geom_line() -->




<!-- ############ -->





<!-- install.packages("OIsurv") -->
<!-- library(OIsurv) -->

<!-- library(help=KMsurv) -->

<!-- data(aids) -->
<!-- glimpse(aids) -->


<!-- data(tongue) -->

<!-- glimpse(tongue) -->

<!-- my.surv.object <- Surv(tongue$time[tongue$type==1], tongue$delta[tongue$type==1]) -->

<!-- my.surv.object -->

<!-- data(psych) -->

<!-- my.surv.object2 <- Surv(psych$age, psych$age+psych$time, psych$death) -->

<!-- my.surv.object2 -->



<!-- ```{r} -->
<!-- library("survival") -->
<!-- fit <- survfit(Surv(time,status) -->
<!-- ~ sex, data = lung) -->
<!-- class(fit) -->
<!-- ## [1] "survfit" -->
<!-- library("survminer") -->
<!-- ggsurvplot(fit, data = lung) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- ggsurvplot(fit, data = lung, fun = "event") -->

<!-- ``` -->


<!-- ```{r} -->
<!-- ggsurvplot(fit, data = lung, fun = "cumhaz") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ggsurvplot(fit, data = lung, -->
<!-- conf.int = TRUE, -->
<!-- pval = TRUE, -->
<!-- fun = "pct", -->
<!-- risk.table = TRUE, -->
<!-- tables.height = 0.3, -->
<!-- size = 0.8, -->
<!-- linetype = "strata", -->
<!-- palette = c("#E7B800", -->
<!-- "#2E9FDF"), -->
<!-- legend = "top", -->
<!-- legend.title = "Sex", -->
<!-- legend.labs = c("Male", -->
<!-- "Female"), -->
<!-- cex = 0.2 -->
<!-- ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- library("survival") -->
<!-- fit <- coxph(Surv(time, status) ~ sex + age, data = lung) -->
<!-- ftest <- cox.zph(fit) -->
<!-- ftest -->
<!-- ``` -->

<!-- ```{r} -->
<!-- library("survminer") -->
<!-- ggcoxzph(ftest) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- library("survival") -->
<!-- library("survminer") -->
<!-- fit <- coxph(Surv(time, status) ~ -->
<!-- sex + age, data = lung) -->

<!-- ``` -->




<!-- ```{r} -->
<!-- ggcoxdiagnostics(fit, -->
<!-- type = "deviance", -->
<!-- ox.scale = "linear.predictions") -->

<!-- ``` -->



<!-- ```{r} -->
<!-- ggcoxdiagnostics(fit, -->
<!-- type = "schoenfeld", -->
<!-- ox.scale = "time") -->
<!-- ``` -->




<!-- # Analysis -->

<!-- ## Survival Analysis -->

<!-- https://github.com/datacamp/tutorial -->

<!-- Based on https://www.datacamp.com/community/tutorials/survival-analysis-R -->


<!-- ```{r} -->
<!-- library(tutorial) -->
<!-- library(survival) -->
<!-- library(survminer) -->
<!-- library(tidyverse) -->
<!-- library(jmv) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- data(ovarian) -->
<!-- glimpse(ovarian) -->
<!-- help(ovarian) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- summary(ovarian) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- varOvarian <- names(ovarian) -->

<!-- ovarian2 <- ovarian %>%  -->
<!--     map_df(as.factor) -->

<!-- jmv::descriptives(ovarian, varOvarian, freq = TRUE) -->

<!-- jmv::descriptives(ovarian2, varOvarian, freq = TRUE) -->

<!-- ``` -->


<!-- ```{r} -->
<!-- # Dichotomize age and change data labels -->
<!-- ovarian$rx <- factor(ovarian$rx,  -->
<!--                      levels = c("1", "2"),  -->
<!--                      labels = c("A", "B")) -->
<!-- ovarian$resid.ds <- factor(ovarian$resid.ds,  -->
<!--                            levels = c("1", "2"),  -->
<!--                            labels = c("no", "yes")) -->
<!-- ovarian$ecog.ps <- factor(ovarian$ecog.ps,  -->
<!--                           levels = c("1", "2"),  -->
<!--                           labels = c("good", "bad")) -->

<!-- jmv::descriptives(ovarian, varOvarian, freq = TRUE) -->

<!-- ``` -->


<!-- ```{r} -->
<!-- # Data seems to be bimodal -->
<!-- hist(ovarian$age) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- ovarian <- ovarian %>% mutate(age_group = ifelse(age >= 50, "old", "young")) -->
<!-- ovarian$age_group <- factor(ovarian$age_group) -->

<!-- varOvarian <- names(ovarian) -->

<!-- jmv::descriptives(ovarian, varOvarian, freq = TRUE) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Fit survival data using the Kaplan-Meier method -->
<!-- surv_object <- Surv(time = ovarian$futime, event = ovarian$fustat) -->
<!-- surv_object -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fit1 <- survfit(surv_object ~ rx, data = ovarian) -->
<!-- summary(fit1) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- ggsurvplot(fit1, data = ovarian, pval = TRUE) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Examine prdictive value of residual disease status -->
<!-- fit2 <- survfit(surv_object ~ resid.ds, data = ovarian) -->
<!-- ggsurvplot(fit2, data = ovarian, pval = TRUE) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Fit a Cox proportional hazards model -->
<!-- fit.coxph <- coxph(surv_object ~ rx + resid.ds + age_group + ecog.ps,  -->
<!--                    data = ovarian) -->
<!-- ggforest(fit.coxph, data = ovarian) + -->
<!--     geom_errorbar(na.rm = TRUE) -->
<!-- ``` -->









