---
title: "The Lesser Known Stars of the Tidyverse"
---

```
slug: the-lesser-known-stars-of-the-tidyverse
tags:
- tidyverse
- R
- Code
categories: []
output: html_notebook
```


*I copied this code just to learn myself. See original links below:*


# Webinar: Tidyverse Exploratory Analysis (Emily Robinson)

<iframe src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2F726282547396228%2Fvideos%2F584417861986887%2F&show_text=1&width=560" width="560" height="529" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media" allowFullScreen="true"></iframe>  


<iframe width="560" height="315" src="https://www.youtube.com/embed/uG3igAGX7UE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  



<iframe width="560" height="315" src="https://www.youtube.com/embed/ax4LXQ5t38k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  


https://hookedondata.org/the-lesser-known-stars-of-the-tidyverse/  

https://www.rstudio.com/resources/videos/the-lesser-known-stars-of-the-tidyverse/  

https://github.com/robinsones/robinsones_blog/blob/master/content/post/multipleChoiceResponses.csv  

https://github.com/robinsones/robinsones_blog/blob/master/content/post/2018-11-16-the-lesser-known-stars-of-the-tidyverse.Rmd  


## Reading in the data

```
{r eval=FALSE, include=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = FALSE, error = TRUE)

library(tidyverse)
library(magrittr)
theme_set(theme_bw())
```




```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses_base <- read.csv("data/multipleChoiceResponses.csv")
```



```
{r eval=FALSE, include=FALSE, echo=TRUE}
# for one column
sum(is.na(multiple_choice_responses_base$Country))
```




```
{r eval=FALSE, include=FALSE, echo=TRUE}
# for five columns
multiple_choice_responses_base %>%
  summarise_at(1:5, ~sum(is.na(.))) 

multiple_choice_responses_base %>%
  summarise_at(vars(GenderSelect:StudentStatus), ~sum(is.na(.))) 

multiple_choice_responses_base %>%
  summarise_at(vars(GenderSelect, Age), ~sum(is.na(.))) 

```



```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses_base %>%
  count(StudentStatus) 
```

Yep. We see here we have a lot of `""` entries instead of NAs. We can correct this with `na_if` from `dplyr`, which takes as an argument what we want to turn into NAs. We can also use `%<>%`, which is a reassignment pipe. While this is nice to save some typing, it can make it confusing when reading a script, so use with caution. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses_base %<>%
  na_if("")

## is the same as: 

multiple_choice_responses_base <- multiple_choice_responses_base %>%
  na_if("")
```

Now let's count the NAs again. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses_base %>%
  summarise_at(1:5, ~sum(is.na(.))) 
```

And it's fixed! 

How could we have avoided this all in the first place? By using `{r # eadr::read_csv` instead of `{r # ead.csv`.

If you're not familiar with `::`, it's for explicitly setting what package you're getting the function on the right from. This is helpful in three ways:

  1) There can be name conflicts, where two packages have functions with the same name. Using `::` ensures you're getting the function you want. 
  2) if you only want to use one function from a package, you can use `::` to skip the library call. As long as you've installed the package, you don't need to have loaded it to get the function. 
  3) For teaching purposes, it's nice to remind people where the function is coming from. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses <- readr::read_csv("multipleChoiceResponses.csv")
```


It's definitely faster, but it seems we have some errors. Let's inspect them. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
problems(multiple_choice_responses)
```

We see each row and column where a problem occurs. What's happening is that `{r # ead_csv` uses the first 1000 rows of a column to guess its type. But in some cases, it's guessing the column is an integer, because the first 1000 rows are whole numbers, when actually it should be double, as some entries have decimal points. We can fix this by changing the number of rows `{r # ead_csv` uses to guess the column type (with the `guess_max` argument) to the number of rows in the data set. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses <- readr::read_csv("multipleChoiceResponses.csv", 
                                             guess_max = nrow(multiple_choice_responses))
```

Error-free!

## Initial examination 

Let's see what we can glean from the column names themselves. I'll only look at the first 20 since there are so many. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
colnames(multiple_choice_responses) %>%
  head(20)
```

We can see that there were categories of questions, like "LearningPlatform," with each platform having its own column.

Now let's take a look at our numeric columns with [skimr](https://github.com/ropensci/skimr). Skimr is a package from [rOpenSci](https://ropensci.org/) that allows you to quickly view summaries of your data. We  can use `select_if`  to select only columns where a certain condition, in this case whether it's a numeric column, is true.  

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses %>%
  select_if(is.numeric) %>%
  skimr::skim()
```

I love the histograms. We can quickly see from them that people self teach a lot and spend a good amount of time building models and gathering data, compared to visualizing data or working in production.   

Let's see how many distinct answers we have for each question. We can use `n_distinct()`, a shorter and faster version of `length(unique())`. We'll use `summarise_all`, which is the same as `summarise_at` except that you don't select a group of columns and so it applies to every one in the dataset.

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses %>%
  summarise_all(n_distinct) %>%
  select(1:10)
```

This data would be more helpful if it was tidy and had two columns, `question` and `num_distinct_answers`. We can use `tidyr::gather` to change our data from "wide" to "long" format and then `arrange` it so we can see the columns with the most distinct answers first. If you've used (or are still using!) reshape2, check out tidyr; reshape2 is retired and is only updated with changes necessary for it to remain on CRAN. While not exactly equivalent, `tidyr::spread` replaces `{r # eshape2::dcast`, `tidyr::separate` `{r # eshape2::colsplit`, and `tidyr::gather` `{r # eshape2::melt`. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses %>%
  summarise_all(n_distinct) %>%
  tidyr::gather(question, num_distinct_answers) %>%
  arrange(desc(num_distinct_answers))
```

Let's take a look at the question with the most distinct answers, WorkMethodsSelect. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
multiple_choice_responses %>%
  count(WorkMethodsSelect, sort = TRUE)
```

We can see this is a multiple select question, where if a person selected multiple answers they're listed as one entry, separated by commas. Let's tidy it up. 

First, let's get rid of the NAs. We can use `!is.na(WorkMethodsSelect)`, short for `is.na(WorkMethodsSelect) == FALSE`, to filter out NAs. We then use `str_split`, from stringr, to divide the entries up. `str_split(WorkMethodsSelect, ",")`  says "Take this string and split it into a list by dividing it where there are `,`s." 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
nested_workmethods <- multiple_choice_responses %>%
  select(WorkMethodsSelect) %>%
  filter(!is.na(WorkMethodsSelect)) %>%
  mutate(work_method = str_split(WorkMethodsSelect, ",")) 

nested_workmethods %>%
  select(work_method)
```

Now we have a list column, with each entry in the list being one work method. We can `unnest` this so we can get back a tidy dataframe. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
unnested_workmethods <- nested_workmethods %>%
  tidyr::unnest(work_method) %>%
  select(work_method)

unnested_workmethods
```

Great! As a last step, let's `count` this data so we can find which are the most common work methods people use. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
unnested_workmethods %>%
  count(work_method, sort = TRUE)
```

We see the classic methods of data visualization, logistic regression, and cross-validation lead the pack. 

### Graphing Frequency of Different Work Challenges 

Now let's move on to understanding what challenges people face at work. This was one of those categories where there were multiple questions asked, all having names starting with `WorkChallengeFrequency` and ending with the challenge (e.g "DirtyData"). 

We can find the relevant columns by using the dplyr `select` helper `contains`. We then use `gather` to tidy the data for analysis, filter for only the non-NAs, and remove the `WorkChallengeFrequency` from each question using `stringr::str_remove`. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
WorkChallenges <- multiple_choice_responses %>%
  select(contains("WorkChallengeFrequency")) %>%
  gather(question, response) %>%
  filter(!is.na(response)) %>%
  mutate(question = stringr::str_remove(question, "WorkChallengeFrequency")) 

WorkChallenges
```

Let's make a facet bar plot, one for each question with the frequency of responses.To make the x-axis tick labels readable, we'll change them to be vertical instead of horizontal. 

```
{r WorkChallenges_graph1, fig.width = 9, fig.height = 6}
ggplot(WorkChallenges, aes(x = response)) + 
  geom_bar() + 
  facet_wrap(~question) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

This graph has two main problems. First, there are too many histograms for it to be really useful. But second, the order of the x-axis is wrong. We want it to go from least often to most, but instead `{r # arely` is in the middle. We can manually reorder the level of this variable using `forcats::fct_relevel`. 

```
{r WorkChallenges_graph2, fig.width = 9, fig.height = 6}
WorkChallenges %>%
  mutate(response = fct_relevel(response, "Rarely", "Sometimes", 
                                "Often", "Most of the time")) %>%
  ggplot(aes(x = response)) + 
  geom_bar() + 
  facet_wrap(~question) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Now we've got the x-axis in the order we want it. Let's try dichotomizing the variable by grouping "most of the time" and "often" together as the person considering something a challenge. We can use `if_else` and `%in%`. `%in%` is equivalent to `{r # esponse == "Most of the time" | response == "Often"` and can save you a lot of typing if you have a bunch of variables to match. 

Grouping by the question, we can use `summarise` to reduce the dataset to one row per question, adding the variable `perc_problem` for the percentage of responses that thought something was a challenge often or most of the time. This way, we can make one graph with data for all the questions and easily compare them. 

```
{r eval=FALSE, include=FALSE, echo=TRUE}
perc_problem_work_challenge <- WorkChallenges %>%
  mutate(response = if_else(response %in% c("Most of the time", "Often"), 1, 0)) %>%
  group_by(question) %>%
  summarise(perc_problem = mean(response)) 
```

```
{r perc_problem_work_challenge_graph, fig.width = 8, fig.height = 5}
ggplot(perc_problem_work_challenge, aes(x = question, y = perc_problem)) + 
  geom_point() +
  coord_flip()
```

This is better, but it's hard to read because the points are scattered all over the place. Although you can spot the highest one, you then have to track it back to the correct variable. And it's also hard to tell the order of the ones in the middle. 

We can use `forcats:fct_reorder` to change the x-axis to be ordered by another variable, in this case the y-axis. While we're at it, we can use `scale_y_continuous` and`scales::percent` to update our axis to display in percent and `labs` to change our axis labels. 

```
{r perc_problem_work_challenge_graph2, fig.width = 8, fig.height = 5}
ggplot(perc_problem_work_challenge, 
       aes(x = perc_problem, 
           y = fct_reorder(question, perc_problem))) + 
  geom_point() +
  scale_x_continuous(labels = scales::percent) + 
  labs(y = "Work Challenge", 
       x = "Percentage of people encountering challenge frequently")
```

Much better! You can now easily tell which work challenges are encountered most frequently. 

### Conclusion

I'm a big advocate of using and teaching the tidyverse for data analysis and visualization in R (it runs [in the family](http://varianceexplained.org/r/teach-tidyverse/)). In addition to doing these talks, I've released a DataCamp course on [Categorical Data in the Tidyverse](https://www.datacamp.com/courses/categorical-data-in-the-tidyverse). I walk through some of the functions in this course and more from forcats. It's part of the new [Tidyverse Fundamentals skill track](https://www.datacamp.com/tracks/tidyverse-fundamentals), which is suitable for people are new to R or those looking to switch to the tidyverse. Check it out and let us know what you think. 

Some other good resources for learning the tidyverse are Hadley Wickham and Garrett Grolemund's free [R for Data Science book](http://r4ds.had.co.nz/) and [RStudio's cheat sheets](https://www.rstudio.com/resources/cheatsheets/). If you have questions, I recommend using the [tidyverse section of RStudio community](https://community.rstudio.com/c/tidyverse) and/or the #rstats hashtag on Twitter. If you do, make sure you include a reproducible example (see best practices [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)) with the [reprex package](https://reprex.tidyverse.org/articles/articles/magic-reprex.html)!

